name: Validate terraform configuration files

on: [pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate
        run: terraform init && terraform validate
